# Generated by Django 3.0.14 on 2024-10-04 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='senha',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='user',
        ),
    ]
